---
- name: Converge
  hosts: all
  tasks:
    - name: "Include auth-duo"
      include_role:
        name: "auth-duo"
      vars:
        auth_duo_settings:
          - key: ikey
            value: "{{ lookup('env','AUTH_DUO_IKEY') }}"
          - key: skey
            value: "{{ lookup('env','AUTH_DUO_SKEY') }}" 
          - key: host
            value: "{{ lookup('env','AUTH_DUO_HOST') }}" 
